# $Id: Rakefile 831 2008-07-19 13:25:03Z kimuraw $
# utilitles for development MacPorts portfiles

# 
require 'fileutils'

# Rake tasks
task :default => ["port:portindex"]

desc %Q!"svn update" at top of port-tree!
task :update do
  sh 'svn update'
end

desc %Q!generate patchfile to trunk!
task :gen_patch do
  sh 'svn diff -r49785:HEAD lang'
end

namespace "port" do
  desc %Q!"portindex" at top of port-tree!
  task :portindex do
    sh 'portindex'
  end
end

